apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo-website-dev
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/demo-website/overlays/dev"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 2m0s
  retryInterval: 1m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo-website-staging
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/demo-website/overlays/staging"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 5m0s
  retryInterval: 2m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-demo-website-prod
  namespace: flux-system
spec:
  interval: 5m
  path: "./apps/demo-website/overlays/prod"
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  timeout: 10m0s
  retryInterval: 5m0s
